# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("fix_duplicate_misspelled_names works", {
  expect_true(inherits(fix_duplicate_misspelled_names, "function")) 
})
