# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("create_health_diagnoses works", {
  expect_true(inherits(create_health_diagnoses, "function"))
})
