# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("download_to_local works", {
  expect_true(inherits(download_to_local, "function"))
})
