# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("has_drive_file_changed works", {
  
  # a test file on google drive provided by the googldrive package
  test_file <- "1X9pd4nOjl33zDFfTjw-_eFL7Qb9_g6VfVFDp1PPae94"

  # today, the file is stable so it should not have changed
  unchanged_time <- ymd_hms("2025-04-01 00:00:00", tz = "UTC")
  expect_false(has_drive_file_changed(test_file, unchanged_time))

  # but if we go back in time to when the file was created, it should
  # have changed since then
  changed_time <- ymd_hms("2021-04-02 00:00:00", tz = "UTC")
  expect_true(has_drive_file_changed(test_file, changed_time))
})
