# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_opensrp_dob works", {
  expect_true(inherits(clean_opencensus_dob, "function")) 
})
