# WARNING - Generated by {fusen} from dev/flat_reporting_pins.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("table_to_pinboard works", {
  expect_true(inherits(table_to_pinboard, "function")) 
})
