# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("preprocess_2018_health works", {
  expect_true(inherits(preprocess_2018_health, "function"))
})
