# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("create_datapaths works", {
  #TODO this test fails because of here() function

  skip_if_not_installed("fs")
  skip_if_not_installed("here")

  # Save current working directory
  old_wd <- getwd()

  # Create a temporary project directory
  temp_proj <- fs::path_temp("test_data_env")
  fs::dir_create(temp_proj)
  setwd(temp_proj)

  # Simulate a project root for `here::here()`
  fs::file_create(".here") # Explicitly create a .here file to mark the project root

  # Force here to use the temporary directory as the root
  here::set_here(temp_proj)

  # Call the function to create data paths
  create_datapaths()

  base <- fs::path("data")
  expected_dirs <- fs::path(base, c("raw", "input", "intermediate", "output"))
  expected_keep_files <- fs::path(expected_dirs, ".gitkeep")
  gitignore_file <- fs::path(base, ".gitignore")

  # Check that all folders were created
  expect_true(all(fs::dir_exists(expected_dirs)))

  # Check that .gitkeep files exist
  expect_true(all(fs::file_exists(expected_keep_files)))

  # Check .gitignore exists and has expected content
  expect_true(fs::file_exists(gitignore_file))
  gitignore_lines <- readLines(gitignore_file)
  expect_true(any(grepl("!raw/.gitkeep", gitignore_lines)))
  expect_true(any(grepl("^\\*$", gitignore_lines))) # Make sure '*' line is there

  # Cleanup
  setwd(old_wd)
  fs::dir_delete(temp_proj)
})
