# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("preprocess_2018 works", {
  expect_true(inherits(preprocess_2018, "function"))
})
