# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("clean_2018_vaccinations works", {
  expect_true(inherits(clean_2018_vaccinations, "function")) 
})
