# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("audit_categorical_cleaning works", {
  expect_true(inherits(audit_categorical_cleaning, "function")) 
})
