# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("generate_uid works", {
  expect_true(inherits(generate_uid, "function")) 
})
