# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("recode_opensrp_education works", {
  expect_true(inherits(recode_opensrp_education, "function")) 
})
