# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("Google authentication works", {
  expect_true(authenticate_google_drive())
})
