# WARNING - Generated by {fusen} from dev/flat_cohort_household_heads.Rmd: do not edit by hand # nolint: line_length_linter.

test_that("preprocess_2018_household_heads works", {
  expect_true(inherits(preprocess_2018_household_heads, "function"))
})
