# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Audit and visualize categorical variable cleaning
#'
#' This function helps audit the transformation of raw categorical data into cleaned categories.
#' It displays a summary table of the mapping from raw to cleaned values, and optionally creates
#' an alluvial plot to visualize how categories have been collapsed or recoded.
#'
#' @param df A data frame containing the raw and cleaned categorical columns.
#' @param raw_col Unquoted column name for the raw, uncleaned categorical variable.
#' @param cleaned_col Unquoted column name for the cleaned or recoded categorical variable.
#' @param var_name Optional character string to name the variable in printed and plotted output.
#' If NULL, the name of `raw_col` is used.
#' @param plot Logical, default `TRUE`. If `TRUE`, an alluvial plot of the mapping is generated.
#'
#' @return A tibble showing the frequency of mappings between raw and cleaned categories.
#' The result is returned invisibly (use `invisible()`), but printed by default for inspection.
#' 
#' @export
audit_categorical_cleaning <- function(df, raw_col, cleaned_col, var_name = NULL, plot = TRUE) {
  var_name <- var_name %||% as.character(substitute(raw_col))

  raw <- df[[deparse(substitute(raw_col))]]
  cleaned <- df[[deparse(substitute(cleaned_col))]]

  mapping <- tibble(
    raw = as.character(raw),
    cleaned = as.character(cleaned)
  ) %>%
    count(raw, cleaned, sort = TRUE)

  cat("\n=== Mapping Table for:", var_name, "===\n")
  print(mapping)

  if (plot) {
    gg <- ggplot(mapping,
           aes(axis1 = raw, axis2 = cleaned, y = n)) +
      geom_alluvium(aes(fill = cleaned), width = 1/12) +
      geom_stratum(width = 1/12, fill = "gray") +
      geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 3) +
      scale_x_discrete(limits = c("Raw", "Cleaned"), expand = c(.05, .05)) +
      theme_minimal() +
      labs(title = paste("Category Collapsing:", var_name),
           y = "Number of Records")
    print(gg)
  }

  invisible(mapping)
}
