# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
audit_categorical_cleaning <- function(df, raw_col, cleaned_col, var_name = NULL, plot = TRUE) {
  var_name <- var_name %||% as.character(substitute(raw_col))

  raw <- df[[deparse(substitute(raw_col))]]
  cleaned <- df[[deparse(substitute(cleaned_col))]]

  mapping <- tibble(
    raw = as.character(raw),
    cleaned = as.character(cleaned)
  ) %>%
    count(raw, cleaned, sort = TRUE)

  cat("\n=== Mapping Table for:", var_name, "===\n")
  print(mapping)

  if (plot) {
    gg <- ggplot(mapping,
           aes(axis1 = raw, axis2 = cleaned, y = n)) +
      geom_alluvium(aes(fill = cleaned), width = 1/12) +
      geom_stratum(width = 1/12, fill = "gray") +
      geom_text(stat = "stratum", aes(label = after_stat(stratum)), size = 3) +
      scale_x_discrete(limits = c("Raw", "Cleaned"), expand = c(.05, .05)) +
      theme_minimal() +
      labs(title = paste("Category Collapsing:", var_name),
           y = "Number of Records")
    print(gg)
  }

  invisible(mapping)
}
