# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Calculate Age Group from Date of Birth
#'
#' @param dob A vector of date-of-birth values (class Date)
#' @param reference_date A single date to calculate age relative to (defaults to today)
#' @return A character vector of age groups
#' @export
calculate_age_group <- function(dob, reference_date = Sys.Date()) {
  if (!inherits(dob, "Date")) stop("Input 'dob' must be a Date vector")

  age <- lubridate::interval(dob, reference_date) / lubridate::years(1)
  age <- floor(age)

  cut(
    age,
    breaks = c(-Inf, 0, 1, 4, 9, 14, 19, 24, 49, 64, Inf),
    labels = c(
      "Under 1",
      "1–4",
      "5–9",
      "10–14",
      "15–19",
      "20–24",
      "25–49",
      "50–64",
      "65+",
      "Unknown"  # this one is just a filler, but not needed unless age has NA
    )[1:10],  # only include 10 labels
    right = TRUE,
    include.lowest = TRUE
  )
}
