# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Clean and standardize date of birth information from OpenCensus data
#'
#' This function processes date of birth fields from OpenCensus survey data, including
#' cleaning inconsistencies, translating French month names, handling likely placeholder
#' values, and producing a unified `Date` column for further analysis.
#'
#' It also flags entries where the date of birth is likely to be estimated or unreliable.
#'
#' @param open_census_ A data frame containing raw date of birth fields, including `dob_date`,
#' `dob_month`, `dob_year`, and `dob_actual`.
#'
#' @return A data frame with the following new or cleaned columns:
#' \describe{
#'   \item{dob_date_clean}{A numeric day value with invalid values (e.g., 999) replaced with 1.}
#'   \item{dob_month_clean}{A numeric month string converted from potentially French or ambiguous month names.}
#'   \item{dob_estimated}{A logical column indicating whether the date is likely estimated.}
#'   \item{dob_clean}{A `Date` object constructed from the cleaned day, month, and year values.}
#' }
#'
#' @details
#' - French month names such as "janvier", "février", and "décembre" are translated to English and then to numeric form.
#' - Dates where `dob_actual == "No"`, `dob_month == "month idr"`, or `dob_date` > 31 are flagged as estimated.
#' - Any `dob_date` greater than 31 (e.g., 999 as a placeholder) is replaced with 1.
#' - If `dob_month` is "month idr", it is assumed to be January for imputation.
#'
#' @importFrom dplyr mutate case_when
#' @importFrom stringr str_to_lower str_replace_all
#' @importFrom lubridate dmy
#'
#' @export
clean_opencensus_dob <- function(open_census_){
  
  open_census_ %>%
    # convert date to numeric and remove any invalid dates
    mutate(dob_date_clean = as.numeric(dob_date)) %>%

    # record any time that the date is likely to be estimated
    mutate(dob_estimated = case_when(
      dob_actual == "No"        ~ TRUE, # if the dob actual is false
      dob_month == "month idr"  ~ TRUE, # if they cannot remember the month
      dob_date_clean > 31       ~ TRUE, # or if the date is 999 (likely a placeholder for NA)
      .default = FALSE
    )) %>%

    # if day is greater than 31, set it to 1 for the estimate
    mutate(dob_date_clean = ifelse(dob_date_clean > 31, 1, dob_date_clean)) %>%

    # convert month from french to english for clarity
    mutate(dob_month_clean = dob_month %>%
      str_to_lower() %>%
      str_replace_all("janvier", "January") %>%
      str_replace_all("février", "February") %>%
      str_replace_all("fevrier", "February") %>%
      str_replace_all("mars", "March") %>%
      str_replace_all("avril", "April") %>%
      str_replace_all("mai", "May") %>%
      str_replace_all("juin", "June") %>%
      str_replace_all("juillet", "July") %>%
      str_replace_all("août", "August") %>%
      str_replace_all("aout", "August") %>%
      str_replace_all("septembre", "September") %>%
      str_replace_all("octobre", "October") %>%
      str_replace_all("novembre", "November") %>%
      str_replace_all("décembre", "December") %>%
      str_replace_all("decembre", "December") %>%
      # if month is idr, set it to january 1st
      str_replace_all("month idr", "January")
    ) %>%

    # convert month in english to numeric for lubridate
    mutate(dob_month_clean = dob_month_clean %>%
      str_to_lower() %>%
      str_replace_all("january", "01") %>%
      str_replace_all("february", "02") %>%
      str_replace_all("march", "03") %>%
      str_replace_all("april", "04") %>%
      str_replace_all("may", "05") %>%
      str_replace_all("june", "06") %>%
      str_replace_all("july", "07") %>%
      str_replace_all("august", "08") %>%
      str_replace_all("september", "09") %>%
      str_replace_all("october", "10") %>%
      str_replace_all("november", "11") %>%
      str_replace_all("december", "12")
    ) %>%
    # convert to date
    mutate(dob_clean = paste0(dob_date_clean, "-", dob_month_clean, "-", dob_year) %>%
      dmy()
    )
}
