# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' health_data_ %>% 
#'   clean_2018_pregnancy() -> health_data_
#'
#' health_data_ %>%
#'   select(matches("pregnancy|birth|deliveries")) %>%
#'   select(contains("clean")) %>%
#'   skimr::skim()
clean_2018_pregnancy <- function(df){

  df %>%
    mutate(
      pregnancy_status_clean = case_when(
        pregnant == "Yes" ~ "Currently_pregnant",
        pregnant == "No" ~ "Not_pregnant",
        TRUE ~ NA_character_
      ) %>% as.factor(),
      number_deliveries_clean = as.numeric(number_deliveries),
      number_live_births_clean = as.numeric(number_live_births),
      most_recent_birthweight_gram_clean = as.numeric(birthweight_gram)
    )
}
