# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @return
#' 
#' @export
#' @examples
#' health_data_ %>% 
#'   create_health_diagnoses() %>%
#'   summary()
create_health_diagnoses <- function(df, diagnosis_lookup=malagasy_diagnosis_lookup_table){

  df %>%
    mutate(prior_diagnosis_ = 
      prior_diagnosis %>% 
        str_to_lower() %>%
        str_replace("infected wound prior diagnosis other", "infected_wound") %>%
        str_replace("malaria cancer", "malaria,cancer") %>%
        str_replace("malaria prior diagnosis other", "malaria") %>%
        str_replace("no pregnancy prior diagnosis other", "no_pregnancy") %>%
        str_replace("no pregnancy", "no_pregnancy") %>%
        str_replace("prior diagnosis other", "other") %>%
        str_replace("hypertension idr", "hypertension") %>%
        str_replace("no diagnosis", NA_character_) %>%
        str_replace("idr", NA_character_)
    ) %>%
    mutate(other_prior_diagnosis = 
      other_prior_diagnosis %>% 
        str_to_lower() %>%
        str_replace("infected wound prior diagnosis other", "infected_wound") %>%
        str_replace("malaria cancer", "malaria,cancer") %>%
        str_replace("malaria prior diagnosis other", "malaria") %>%
        str_replace("no pregnancy prior diagnosis other", "no_pregnancy") %>%
        str_replace("no pregnancy", "no_pregnancy") %>%
        str_replace("prior diagnosis other", "other") %>%
        str_replace("hypertension idr", "hypertension") %>%
        str_replace("no diagnosis", NA_character_) %>%
        str_replace("idr", NA_character_)
    ) %>%
    unite(diagnoses_all, prior_diagnosis_, other_prior_diagnosis, sep = ",", remove=FALSE, na.rm=TRUE) %>%
    mutate(
      diagnoses_all = 
        str_squish(diagnoses_all) %>% 
          str_replace(", ", ",") %>%
          str_replace(" ", "_") %>%
          # if it just starts with "other," it means it has only "other diagnosis"
          # and can be safely removed
          str_replace("^other,", "") %>%
          # which means the ones that are 999 are true "other" diagnoses
          # with no specification in english
          str_replace("999", "other_unspecified")
    ) %>%
    mutate(diagnoses_all = na_if(diagnoses_all, "")) %>%

    # step 1: Unnest and match diagnoses
    mutate(id = row_number()) %>%
    separate_rows(diagnoses_all, sep = ",") %>%
    mutate(diagnoses_all = str_trim(diagnoses_all)) %>%
    left_join(diagnosis_lookup, by = c("diagnoses_all" = "raw")) %>%
    filter(!is.na(diagnosis_english)) -> long_df

    # Step 2: Create wide one-hot matrix
    wide_matrix <- long_df %>%
      mutate(present = 1) %>%
      distinct(id, diagnosis_english, present) %>%
      pivot_wider(names_from = diagnosis_english, values_from = present, values_fill = 0)

    # Step 3: Join back to original data
    output <- df %>%
      mutate(id = row_number()) %>%
      left_join(
        long_df %>%
          group_by(id) %>%
          summarise(
            diagnosis_english = paste(unique(diagnosis_english), collapse = ", "),
            diagnosis_icd10_code = paste(unique(icd10_code), collapse = ", ")
          ),
        by = "id"
      ) %>%
      left_join(wide_matrix, by = "id") %>%
      select(-id)

    return(output)
}
