# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' Create Data Directory Structure for Reproducible Pipelines
#'
#' Creates a standard data folder structure at the project root:
#' data/raw/, data/input/, data/intermediate/, data/output/
#' Adds a .gitignore to exclude files but keep the folder structure.
#'
#' @importFrom here here
#' @importFrom fs dir_create file_create path
#' @export
#' @examples
#' if(FALSE) {
#'   create_datapaths()
#' } 
create_datapaths <- function() {
  # Define main data directory and subdirectories
  base_dir <- here::here("data")
  subdirs <- c("raw", "input", "intermediate", "output")
  full_paths <- fs::path(base_dir, subdirs)

  if (all(fs::dir_exists(full_paths))) {
    message("✅ Directories already exist.")
    return(TRUE)
  }

  # Create folders
  fs::dir_create(full_paths)

  # Create .gitkeep files in each subdir to keep them in version control
  fs::file_create(fs::path(full_paths, ".gitkeep"))

  # Write .gitignore at data/ level
  gitignore_path <- fs::path(base_dir, ".gitignore")
  gitignore_content <- c(
    "# Ignore all data files",
    "*",
    "# But keep these folders (and their .gitkeep files)",
    "!*/",
    "!raw/.gitkeep",
    "!input/.gitkeep",
    "!intermediate/.gitkeep",
    "!output/.gitkeep"
  )
  writeLines(gitignore_content, gitignore_path)

  # Check if all directories were created successfully
  if (!all(fs::dir_exists(full_paths))) {
    message("❌ Failed to create some directories.")
    return(FALSE)
  } else {
    message("✅ Data environment initialized at: ", base_dir)
    return(TRUE)
  }

}
