# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' download_to_local
#'
#' Download the google drive file to local storage
#'
#' @importFrom googledrive drive_find drive_download
#' @importFrom dplyr pull
#'
#' @return The path to the downloaded file
#'
#' @export
#' @examples
#' authenticate_google_drive()
#' test_file <- "openSRP_dictionary.xlsx"
#' fpath <- download_to_local(test_file, here::here())
#' file.exists(fpath)
#' file.remove(fpath)
download_to_local <- function(f_regex, download_dir) {
  # Find the file on Google Drive
  file_info <- drive_find(f_regex, n_max = 1)

  if (nrow(file_info) == 0) {
    stop("No file found matching the regex: ", f_regex)
  }

  # Extract the file name from Google Drive metadata
  file_name <- file_info$name

  # Construct the full path for the local file
  local_path <- file.path(download_dir, file_name)

  if (file.exists(local_path)) {
    message("File already exists locally: ", local_path)
    return(local_path)
  }

  # Download the file to the specified path
  drive_download(as_id(file_info$id), path = local_path, overwrite = FALSE)

  if (!file.exists(local_path)) {
    stop("File not downloaded successfully.")
  } else {
    message("File downloaded successfully to: ", local_path)
  }

  return(local_path)
}
