# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Add ordinal suffixes to repeated household head names by date
#'
#' This function modifies a data frame by appending Roman numeral suffixes
#' (e.g., " ii", " iii") to a specific household head name that appears more than once.
#' The suffixes are added in chronological order based on a date column, beginning with
#' the second occurrence. Only the specified name is modified; all others remain unchanged.
#'
#' @param df A data frame containing at least the household name and date columns.
#' @param target_name A character string specifying the exact name to deduplicate and label (e.g., "be zela").
#' @param name_col A column in `df` that contains the household head names. Defaults to `hh_head_name_clean`.
#' @param date_col A column in `df` that contains an identifier for the recorded date. Defaults to `submission_date`.
#'
#' @return A data frame with the specified name deduplicated by date, using ordinal suffixes.
#' Other names remain unchanged.
#' 
#' @export
#' @examples
#' open_census_ %>%
#'   fix_duplicate_misspelled_names(name_col = name_family_member_clean, 
#'                                  hh_col = hh_head_name_clean) -> open_census_
fix_duplicate_misspelled_names <- function(df, name_col = name, hh_col = hh_head_name) {
  name_col_sym <- rlang::enquo(name_col)
  hh_col_sym <- rlang::enquo(hh_col)

  # Hand-curated corrections
  correction_map <- tibble::tibble(
    name = c(
      "be jenore", "juliette", "berthine", "bevita", "jean bemiao", 
      "jean erique", "marrgelin", "orelin frasoa", "philippe", 
      "raherimanana jean fredo", "randriamanantena", 
      "ravalomanana junel", "jean yves", "rozadison jean barthelemy",
      "tianavelo zara aime", "avoavy clovis", "zenal ture", "emilien", "geralson", "randrianasoavina"
    ),
    corrected = c(
      "be jenole", "be juliette", "bertine", "bsvita", "jan bemiao",
      "jean ericque", "margelin", "orelin françois", "phillippe",
      "raherimananajean fredo", "randriamanantena honorat",
      "ravalomanana junelle", "renaud", "rozaddison jean barthelemy",
      "tianavelo", "voavy clovis", "zanal ture", "emillien", "geralison", "randrianasoaviana"
    )
  )

  df %>%
    dplyr::left_join(correction_map, by = setNames("name", rlang::as_name(name_col_sym))) %>%
    dplyr::mutate(!!rlang::as_name(name_col_sym) := dplyr::coalesce(corrected, !!name_col_sym)) %>%
    dplyr::select(-corrected) %>%

    # set eddy ii to corrected name
    dplyr::mutate(!!rlang::as_name(name_col_sym) := 
      dplyr::case_when(
        !!name_col_sym == "eddy" & str_starts(id, "A3dd6eda") ~ "eddy ii",
        TRUE ~ !!name_col_sym
      )) %>%
    dplyr::mutate(!!rlang::as_name(hh_col_sym) := 
      dplyr::case_when(
        str_starts(id, "A3dd6eda") ~ "eddy ii",
        str_starts(id, "48149ba9") ~ "kalo jeannette",
        TRUE ~ !!hh_col_sym
      ))
}
