# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Title
#' 
#' Description
#' 
#' @importFrom digest digest
#' 
#' @return
#' 
#' @export
#' @examples
#' generate_uid(salt = "cohort_secret", "John", "Doe", "1990-01-01")
generate_uid <- function(salt = "cohort_secret", ..., nchar=6) {
  input <- paste(salt, ..., sep = "_")
  uid <- substr(digest(input, algo = "sha256"), 1, nchar)  # 12-char unique ID
  return(uid)
}
