# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' has_drive_file_changed
#'
#' Check from a file modification timestamp whether or not it has been changed
#' since last run of the pipeline.
#'
#' @param file_id The ID of the file to check
#' @param last_known_run_time The last known time the pipeline was frozen for running
#'
#' @return Boolean
#'
#' @export
#' @importFrom googledrive drive_get as_id
#' @importFrom lubridate ymd_hms
#' @examples
#' test_file <- "1X9pd4nOjl33zDFfTjw-_eFL7Qb9_g6VfVFDp1PPae94"
#' has_drive_file_changed(test_file, lubridate::ymd_hms("2025-04-01 00:00:00", tz = "UTC"))
has_drive_file_changed <- function(
  drive_resource,
  last_known_run_time = ymd_hms("2025-04-01 00:00:00", tz = "UTC")
) {
  if (!authenticate_google_drive()) {
    stop(
      "Authentication failed. Please check the path to the authentication file."
    )
  }

  current_time <- ymd_hms(drive_resource$modifiedTime, tz = "UTC")
  return(current_time > last_known_run_time)
}
