# WARNING - Generated by {fusen} from dev/flat_tracking_inputs.Rmd: do not edit by hand # nolint: line_length_linter.

#' Track the Input Files for the Mahery Cohort
#'
#' Description
#'
#' @return tibble with the file names and their regex patterns
#' @importFrom lubridate mdy
#' @importFrom tibble tribble
#'
#' @export
mahery_input_files <- function(freeze_date = mdy("01-04-2025")) {
  tribble(
    ~fname,
    ~regex,
    ~freeze_date,
    "2018_data",
    "openSRP_data_2018*",
    freeze_date,
    "2018_dictionary",
    "openSRP_dictionary*",
    freeze_date,
    "2019_beyond",
    "Dharma_2019*",
    freeze_date,
    "2019_data",
    "Dharma_followup*",
    freeze_date
  )
}
