# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' preprocess_2018_health Title
#'
#' @return 1
#' @export
#'
#' @examples
#' preprocess_2018_health()
preprocess_2018_health <- function() {
  1
}
