# WARNING - Generated by {fusen} from dev/flat_cohort_household_heads.Rmd: do not edit by hand # nolint: line_length_linter.

#' preprocess_2018_household_heads Preprocess 2018 Household Heads
#'
#' @return Tibble with cleaned household head data
#' @export
#' @examples
#' preprocess_2018_household_heads(opensrp, cohort_2018) %>%
#'   summary()
preprocess_2018_household_heads <- function(opensrp, cohort_2018) {
  hhreg <- opensrp$Hhregistration
  hhreg %>%
    janitor::clean_names() %>%
    mutate(
      hh_head_name = str_to_lower(name_household_head) %>%
        str_squish() %>%
        str_remove_all(",")
    ) %>%
    mutate(submission_date = ymd(submission_date)) %>%
    select(
      original_id = id,
      hh_head_name,
      submission_date,
      village,
      province,
      district
    ) %>%
    mutate(across(where(is.character), as_factor)) -> hhreg_

  hh_geography <- opensrp$GPS
  hh_geography %>%
    janitor::clean_names() %>%
    mutate(
      hh_head_name = str_to_lower(head_of_household) %>%
        str_squish() %>%
        str_remove_all("\\(") %>%
        str_remove_all("\\)") %>%
        str_remove_all(",")
    ) %>%
    separate(
      gps_point,
      into = c("gps_latitude", "gps_longitude", "gps_altitude", "gps_accuracy"),
      sep = " ",
      convert = TRUE
    ) %>%
    mutate(has_gps = !is.na(gps_latitude) & !is.na(gps_longitude)) %>%
    filter(has_gps) %>%
    select(hh_head_name, gps_latitude:gps_accuracy) %>%
    mutate(across(where(is.character), as_factor)) -> hh_geography_

  # Join
  hhreg_ %>%
    left_join(hh_geography_, by = "hh_head_name") %>%
    mutate(
      hh_head_name = case_when(
        hh_head_name == "kalo jsannette" ~ "kalo jeannette",
        hh_head_name == "emilien" ~ "emillien",
        hh_head_name == "randrianasoavana" ~ "randrianasoaviana",
        str_starts(original_id, "A3dd") ~ "eddy ii",
        TRUE ~ hh_head_name
      )
    ) %>%
    left_join(
      cohort_2018 %>%
        select(uuid, name, hh_head_name, original_id),
      join_by(original_id == original_id, hh_head_name == name)
    ) %>%
    select(-hh_head_name.y) %>%
    # there are two cases that come out with NA. In the first, it is `hervet`, which we can
    # assume was hervet testing the system. In the second, it is tsidinesana, which is an
    # actual duplicate in the data.
    filter(!is.na(uuid)) -> hhreg_final

  hhreg_final
}
