# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' preprocess_2018_health Title
#'
#' @return 1
#' @export
#'
#' @examples
#' preprocess_2018_health(open_census, cohort_2018_deid) -> health_data_
#'
#' skim(health_data_)
preprocess_2018_health <- function(open_census, cohort_2018_deid, diagnosis_lookup = malagasy_diagnosis_lookup_table) {
  
  open_census %>%
    clean_names() %>%
    filter(!str_detect(member, "36841201")) %>%
    select(prior_health_care:deathyear) %>%
    bind_cols(select(cohort_2018_deid, uuid_clean = uuid, sex_clean = sex, age_group_clean = age_group), .) -> health_data

  health_data %>%
    create_health_diagnoses(., diagnosis_lookup = diagnosis_lookup) %>%
    clean_2018_vaccinations() %>%
    clean_2018_pregnancy() %>%
    mutate(
      surgical_history_clean = case_when(
        surgeries == "Yes" ~ TRUE,
        surgeries == "No" ~ FALSE,
        TRUE ~ NA
      ),
      surgery_description_clean = case_when(
        # values taken from the table() of the prior_surgeries column
        is.na(prior_surgeries)                                              ~ NA_character_,
        prior_surgeries == "&"                                              ~ NA_character_,
        str_detect(prior_surgeries, "Niterak.*nididiana|Niterak nodidiana") ~ "Cesarean section",
        str_detect(prior_surgeries, "apandisite")                           ~ "Appendectomy",
        str_detect(prior_surgeries, "Voakiso.*tanan")                       ~ "Injury - hand trauma",
        str_detect(prior_surgeries, "famaky.*tongotra|lasety.*tongotra")    ~ "Injury - foot laceration",
        str_detect(prior_surgeries, "kakazo.*kirandra")                     ~ "Injury - ankle trauma",
        str_detect(prior_surgeries, "omb.*kibo")                            ~ "Injury - animal trauma (zebu)",
        TRUE ~ "Other / Unknown"
      ),
      deformities_clean = case_when(
        is.na(visual_health_deformities)              ~ NA_character_,
        visual_health_deformities == "Deformities na" ~ NA_character_,
        !is.na(visual_health_deformities) & !is.na(other_visual_health_deformities) ~ str_c(visual_health_deformities, ", ", other_visual_health_deformities),
        TRUE ~ visual_health_deformities
      )
    ) %>%
    select(contains("clean")) %>%
    rename_with(
      ~ str_replace(., "_clean$", ""),
      everything()
    )
  
}
