# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Pipeline Step to Preprocess Open Census 2018 Data
#' 
#' This function wraps up the preprocessing decisions made in the notebook Cohort 2018 Preprocessing
#' into a single function. This function is then integrated into the {targets} pipeline in _targets.R.
#' 
#' @seealso \href{../articles/cohort-2018-preprocessing.html}{Vignette: Cohort 2018 Preprocessing}
#' 
#' @return tibble
#' 
#' @export
#' @examples
#' preprocess_opensrp2018(open_census) %>% summary()
preprocess_opensrp2018 <- function(open_census){
    
  open_census %>%
    clean_names() %>%
    mutate(village_clean = user_id %>% str_to_lower()) %>%
    mutate(hh_head_name_clean = hh_head_name %>%
      str_to_lower() %>%
      str_squish() %>%
      str_remove_all(",")
    ) %>%
    mutate(name_clean = name_family_member %>%
      str_to_lower() %>%
      str_squish() %>%
      str_remove_all(",")
    ) %>%
    clean_opencensus_dob() %>%
    mutate(ethnicity_clean =
      case_when(
        is.na(ethnic_group)     ~ other_ethnic_group,
        ethnic_group == "Ethnic group other" ~ other_ethnic_group,
        .default = ethnic_group
      ) %>% str_to_lower() %>% as_factor()
    ) %>%
    recode_opensrp_education() %>%
    mutate(employment_status_clean = 
      case_when(
        str_to_lower(profession) == "not working" ~ "inactive",
        str_to_lower(profession) == "occupation"  ~ "employed",
        str_to_lower(profession) == "too young"   ~ "not applicable",
        TRUE ~ NA_character_

      ) %>% as.factor()
    ) %>%
    mutate(
      profession_clean = case_when(
        str_detect(str_to_lower(profession_choices), "farmer") ~ "farmer",
        str_detect(str_to_lower(profession_choices), "shop owner") ~ "shop owner",
        str_detect(str_to_lower(profession_choices), "teacher") ~ "teacher",
        str_detect(str_to_lower(profession_choices), "student") ~ "student",
        TRUE ~ NA_character_
      ) %>% as.factor()
    ) %>%
    mutate(marital_status_clean = marital_status %>% str_to_lower() %>% as_factor()) %>%
    mutate(sex_clean =  sex %>% str_to_lower() %>% as_factor()) %>%
    fix_duplicate_misspelled_names(name_col = name_clean, 
                                 hh_col = hh_head_name_clean) %>%
    mutate(original_id_clean = id) %>%
    mutate(submission_date_clean = ymd(submission_date)) %>%
    mutate(age_group_clean = calculate_age_group(dob_clean)) %>%
    select(contains("clean")) %>%
    select(-dob_date_clean, -dob_month_clean) %>%
    rename_all(~ str_replace(., "_clean", "")) %>%
    rowwise() %>%
    mutate(uuid = generate_uid(salt=Sys.getenv("UUID_SALT"), name, hh_head_name, as.character(dob))) %>%
    ungroup() %>%
    # this removes one row of duplicates from bilina victor
    distinct() %>%
    select(uuid, everything())
}
