# WARNING - Generated by {fusen} from dev/flat_preprocess_2018_health.Rmd: do not edit by hand # nolint: line_length_linter.

#' Malagasy Diagnosis Lookup Table
#' 
#' A lookup table mapping raw diagnosis entries (from Malagasy or English inputs)
#' to standardized English diagnosis labels and ICD-10 chapter-level codes.
#'
#' Used in conjunction with `create_health_diagnoses()` to clean and harmonize
#' multi-source survey data (e.g., `prior_diagnosis`, `other_prior_diagnosis`, or `diagnoses_all`).
#'
#' @format A tibble with 3 columns:
#' \describe{
#'   \item{raw}{Raw input string from survey data}
#'   \item{diagnosis_english}{Cleaned harmonized English label}
#'   \item{icd10_code}{ICD-10 chapter or block code (e.g. "K00–K95")}
#' }
#' @source Manually curated from OpenSRP 2018 health survey entries in the \link[=preprocessing-2018-health-status]{Health Preprocessing} vignette.
"malagasy_diagnosis_lookup_table"
