# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Recode and order education levels from OpenSRP data
#'
#' This function recodes raw education responses from OpenSRP datasets into
#' standardized, English-labeled education levels. It also converts the result
#' into an ordered factor reflecting increasing levels of formal education.
#'
#' @param df A data frame that includes a column named `education`, containing
#' raw education labels such as `"Epp"`, `"Ceg"`, `"Lycee"`, `"University"`, or `"None"`.
#'
#' @return A data frame with two additional columns:
#' \describe{
#'   \item{education_level}{A character vector with recoded education categories.}
#'   \item{education_level_clean}{An ordered factor with levels:
#'     \code{"no_formal_education"} < \code{"primary"} < \code{"lower_secondary"} <
#'     \code{"upper_secondary"} < \code{"higher_education"}.}
#' }
#'
#' @details
#' The recoding is based on the following mapping:
#' \tabular{ll}{
#'   "Epp"       \tab "primary"\cr
#'   "Ceg"       \tab "lower_secondary"\cr
#'   "Lycee"     \tab "upper_secondary"\cr
#'   "University"\tab "higher_education"\cr
#'   "None"      \tab "no_formal_education"
#' }
#'
#' @importFrom dplyr mutate recode
#' @importFrom forcats fct_relevel
#' 
#' @export
recode_opensrp_education <- function(df){

    # Define the label mapping
    education_map <- c(
      "Epp"   = "primary",
      "Ceg"   = "lower_secondary",
      "Lycee" = "upper_secondary",
      "University"  = "higher_education",
      "None"  = "no_formal_education"
    )

    education_levels <- c(
      "no_formal_education",
      "primary",
      "lower_secondary",
      "upper_secondary",
      "higher_education"
    )

    # Recode and create an ordered factor
    df <- df %>%
      mutate(
        education_level = recode(education, !!!education_map),
        education_level_clean = fct_relevel(education_level, !!!education_levels)
      )

    return(df)
}
