# WARNING - Generated by {fusen} from dev/flat_preprocess_2018.Rmd: do not edit by hand # nolint: line_length_linter.

#' Recode OpenSRP Education Levels
#' 
#' Description
#' 
#' @return
#' 
#' @export
recode_opensrp_education <- function(df){

    # Define the label mapping
    education_map <- c(
      "Epp"   = "primary",
      "Ceg"   = "lower_secondary",
      "Lycee" = "upper_secondary",
      "University"  = "higher_education",
      "None"  = "no_formal_education"
    )

    education_levels <- c(
      "no_formal_education",
      "primary",
      "lower_secondary",
      "upper_secondary",
      "higher_education"
    )

    # Recode and create an ordered factor
    df <- df %>%
      mutate(
        education_level = recode(education, !!!education_map),
        education_level_clean = fct_relevel(education_level, !!!education_levels)
      )

    return(df)
}
