# WARNING - Generated by {fusen} from dev/flat_reporting_pins.Rmd: do not edit by hand # nolint: line_length_linter.

#' Upload output to Google Drive pin board or shared folder
#'
#' This function standardizes how we publish outputs from the pipeline
#' to a shared Google Drive folder. If the object is text-compatible
#' (data frames, CSVs, R objects), it uses `pins::pin_write()` for
#' versioning. If it's a binary file (e.g., image, PDF), it uses
#' `googledrive::drive_upload()` instead.
#'
#' @param object The R object or file path to upload.
#' @param name Name to save the object under (used for filename or pin name).
#' @param description A human-readable description (used in pin metadata).
#' @param board A `pins_board` object created by `board_gdrive()`.
#' @param as_file If `TRUE`, upload directly to Drive; otherwise use `pins`.
#' @param type File type (e.g. "csv", "rds", "png"). Only needed for `pins`.
#'
#' @return A message indicating success and upload details.
#' @export
#' @examples
#' # Example usage of to_pinboard function
#' to_pinboard(
#'   object = mtcars,
#'   name = "mtcars",
#'   description = "A dataset of motor trend car road tests",
#'   board = mahery_board,
#'   as_file = FALSE,
#'   type = "csv"
#' )
to_pinboard <- function(object, name, description, board, as_file = FALSE, type = "rds") {
  
  if (as_file) {
    # If object is a file path, upload directly
    stopifnot(fs::file_exists(object))

    googledrive::drive_upload(
      media = object,
      path = board$dribble$id,  # Note: board$path is the Google Drive folder ID
      name = name,
      type = mime::guess_type(object) %||% "application/octet-stream",
      overwrite = TRUE
    )
    message(glue::glue("✅ Uploaded file '{name}' to Google Drive folder. Description:\n{description}"))
  } else {
    # Use pins (best for data frames, R objects, etc.)
    board %>%
      pins::pin_write(
        x = object,
        name = name,
        description = description,
        type = type
      )
    message(glue::glue("📌 Pinned object '{name}' to pin board"))
  }
}
